name: API Front Door Ticket
description: Create an API front door submission
title: "[APIFD]: "
labels: ["apifd"]
assignees:
  - kevintelus
body:
  - type: markdown
    attributes:
      value: |
        This is the first step in the API onboarding process to Kong.  A request should be submitted for:
        * Onboarding new or updated APIs to Kong
        * Engagement with IA for guidance on IA approach
  - type: textarea
    id: summary
    attributes:
      label: description
      description: Describe your changes
    validations:
      required: true
  - type: textarea
    id: apiname
    attributes:
      label: API name
      description: Provide name(s) of proposed API(s) if you know them.  They will be updated to the actual API name(s) later on once they are finalized.
      placeholder:
      value:
    validations:
      required: true
  
