name: Self-serve API Front Door Ticket
description: Create a self-serve API front door ticket
title: 
labels: ["self-serve"]
assignees:
  - kevintelus
body:
  - type: markdown
    attributes:
      value: |
        YOU MUST SUBMIT 1 ISSUE PER API
        By choosing this self-serve form, you are opting out of engagement with IA. The API design is subject to auditing and scoring after onboarding.
  - type: checkboxes
    id: selfserve-check
    attributes:
      label: Self-serve agreement
      description: By submitting this issue, you agree to self-serve API onboarding.
      options:
        - label: I acknowledge that I am opting out of IA engagement for my API design.
          required: true
  - type: textarea
    id: summary
    attributes:
      label: Description
      description: "Provide details about your API (description, purpose, proposal, etc.)"
    validations:
      required: true
  - type: textarea
    id: apiname
    attributes:
      label: API name
      description: "Provide a name for your API.  This may be updated later when your API is finalized."
      placeholder:
      value:
    validations:
      required: true
  - type: input
    id: api-version
    attributes:
      label: API version
      description: "Provide the proposed version number (#.#)"
      placeholder: "1.2"
      value:
    validations:
      required: false
  - type: dropdown
    id: category
    attributes:
      label: API Category
      description: What category does your API belong in?
      options:
        - Experience
        - Task
        - Entity
        - System
    validations:
      required: true
  - type: input
    id: wbscode
    attributes:
      label: WBS code
      description: "Some charges may be required for engagement and assessment.  Depending on the complexity of hte engagement this could range between 1 day to 1 week."
      placeholder:
      value:
    validations:
      required: true
        
  
