on: issues

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Check self-serve
        run: |
          echo "Issue self-serve: ${{ github.event.issue.selfserveflag }}"
          
# You also can print the whole github context to the logs to view more details.
#      - name: View the github context
#        run: echo "$GITHUB_CONTEXT"
#        env:
#          GITHUB_CONTEXT: ${{ toJson(github) }}
